### ISSUE TITLE
feat(patch): Remove transcript button

### ISSUE THREAD

**Issue by Drahy** [YT-Advanced/RVX_BUG_CENTER#1]
### Application

YouTube

### Issue

Removal of transcript button from the youtube player.
Tested on this video https://youtu.be/YFxDzOeHH2M and on Youtube 18.31.40 + 2.188.0 patches

### Patch

![Screenshot_20230814_144111_YouTube](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/810687/06a9494c-0b9d-4561-b717-fe27c588c96b)

![Screenshot_20230814_144116_YouTube](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/810687/a69e03e1-84df-4a75-acb5-421280fc55e1)

### Motivation

All can choose which Icons to show or not. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by girshcatt** [comment]
Sorry this repository is not for yt advanced issues, close this issue here, and copypaste it to YT-Advanced repository issues

**Comment by YT-Advanced** [comment]
> Sorry this repository is not for yt advanced issues, close this issue here, and copypaste it to YT-Advanced repository issues

@girshcatt I said him to report there 🥲

**Comment by girshcatt** [comment]
Oh, sorry( I didn't know this

**Comment by YT-Advanced** [comment]
Added in latest update !
