### ISSUE TITLE
a splash animation is played even if I did not included the relevant patches

### ISSUE THREAD

**Issue by nullll1** [YT-Advanced/RVX_BUG_CENTER#10]
### Type

Error at runtime

### Tools used

rvx-builder

### Application

rvx 19.02.39

### Bug description

I excluded the Enable new splash animation patch and Add splash animation patch, when open YouTube the new splash is still played

### Steps to reproduce

Step 1 select YouTube 19.02.39 apk
Step 2 exclude the Enable new splash animation patch and Add splash animation patch

![Screenshot_20240126-205505](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/102777708/a5f35b02-d9a6-448d-bb86-e92b7875b476)

### Relevant log output

```shell
no log
```

### Screenshots or videos

https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/102777708/3c8591db-6ffd-48c8-951f-ec297e670221

### Device Environment

Android 14, pixel 5

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by YT-Advanced** [comment]
YouTube is applying the splash animation for all YouTube users.
