### ISSUE TITLE
bug: <Keep Landscape Mode Problem>

### ISSUE THREAD

**Issue by sr-shishir** [YT-Advanced/RVX_BUG_CENTER#11]
### Type

Other

### Tools used

rvx-builder

### Application

YouTube 19.02.39
Issue occurs in landscape mode.

### Bug description

When turn off screen & turn on screen in a sec. it becomes to portrait mode. I extend the timeout period from 3000 to 600000 milliseconds but though it’s not working. 

### Steps to reproduce

Fix this issue

### Relevant log output

```shell
"default_video_quality_mobile": 720,
"default_video_quality_wifi": 1080,
"enable_save_playback_speed": true,
"enable_swipe_auto_brightness": true,
"external_downloader_package_name": "com.snaptube.premium",
"hide_autoplay_button": false,
"hide_cast_button": false,
"hide_create_button": false,
"hide_end_screen_cards": true,
"keep_landscape_mode": true,
"keep_landscape_mode_timeout": 600000,
"overlay_button_copy_video_url": true,
"overlay_button_copy_video_url_timestamp": true,
"overlay_button_external_downloader": true,
"overlay_button_speed_dialog": true,
"swipe_brightness_value": -1,
"switching_create_notification": false
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by MondayNitro** [comment]
it is experimental feature so doesnt always work
