### ISSUE TITLE
suggestion: Various additions to the YouTube Interface if possible

### ISSUE THREAD

**Issue by SunSea88** [YT-Advanced/RVX_BUG_CENTER#12]
### Application

YouTube

### Description

Hello,

On your side, do you think that it's possible for you to add these following new options for enhanced comfort on YouTube Android please ?

1 Expand automatically the broadcast date, the video description, the long comments under video and the long community posts like this script on YouTube PC
-> greasyfork.org/fr/scripts/446954-youtube-expand-description-and-long-comments-show-all-the-replies

2 Show again the Username in comments, community posts... instead of User ID Handle with @ like this script on YouTube PC
-> greasyfork.org/fr/scripts/468740-restore-youtube-username-from-handle-to-custom

3 Hide the Most Replayed section in the videos like with uBlockOrigin on YouTube PC
-> droidwin.com/how-to-disable-youtube-most-replayed-feature

4 Put the Timestamps back in the livechat like on YouTube PC

Thank you in advance

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
1. When you expand the comments, it will open in another tab instead of loading reply below the main comments. So it is imposiable
2. In the past, inotia did the same thing in YTM and successully, but ... it have performance issues. 
3. Is it something that very annyoying
4. What is the timestamp you are mentioning

**Comment by SunSea88** [comment]
Okay, I understand...

These timestamps :

![2024-02-04_060449](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/143971989/1886f3ea-5f43-4d25-ac04-6e3511a46047)

![2024-02-04_064258 - Copie](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/143971989/395aec69-f342-4008-b50c-e33a0273cdaa)

**Comment by YT-Advanced** [comment]
Hmm, it may need to use additional API to fetch the data, which is very inefficience
