### ISSUE TITLE
question: <title>: add premade header samples to rvx/rex

### ISSUE THREAD

**Issue by MondayNitro** [YT-Advanced/RVX_BUG_CENTER#13]
### Application

YouTube

### Description

are you willing to add custom headers for rex with revancify icons? i made a sample, if youre willing i will make the remaining
![Screenshot 2024-01-28 023559](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/87489540/dcbc9473-e89a-42a2-98fd-2c67e08874fc)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
Hmm seem great, but I will use the Heading from Rohan

**Comment by YT-Advanced** [comment]
Now I wonder how it look like when applied into YouTube, here is current header:
![image](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/70064328/077dcc1c-60c7-4612-8d81-bb1fc813eb66)

**Comment by YT-Advanced** [comment]
Done
