### ISSUE TITLE
No reboot dialog after alternative thumbnails settings

### ISSUE THREAD

**Issue by User-noob2036876** [YT-Advanced/RVX_BUG_CENTER#2]
### Type

Other

### Tools used

rvx-builder

### Application

Latest

### Bug description

No reboot dialog after alternative thumbnails settings

https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/117031829/bb08abef-fe25-4211-90d4-1ff5a7a3edc7

### Steps to reproduce

not important

### Relevant log output

```shell
not important
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by User-noob2036876** [comment]
Also, this repo can be added to app via "Support Center" like inotia's rvx

**Comment by YT-Advanced** [comment]
No need to restart. It will applied new thumbnail when you refresh the page

**Comment by User-noob2036876** [comment]
> No need to restart. It will applied new thumbnail when you refresh the page

Refresh not changes anything but waiting in app after refreshing changes thumbnail ¿

**Comment by YT-Advanced** [comment]
> > No need to restart. It will applied new thumbnail when you refresh the page
> 
> Refresh not changes anything but waiting in app after refreshing changes thumbnail ¿

it is hard to see the different. But you can turn off then go to an example channel (like Tom Scott). Then turn on it and go back

**Comment by User-noob2036876** [comment]
> > > No need to restart. It will applied new thumbnail when you refresh the page
> > 
> > 
> > Refresh not changes anything but waiting in app after refreshing changes thumbnail ¿
> 
> it is hard to see the different. But you can turn off then go to an example channel (like Tom Scott). Then turn on it and go back

It is not hard to see the difference.
It just changes thumbnail to video's beggin/middle/end

**Comment by YT-Advanced** [comment]
> It is not hard to see the difference. It just changes thumbnail to video's beggin/middle/end

Right, it is how this feature work. Some channel added sensationalism thumbnail for their video. So change thumbnail to the video's beggin/middle/end should be better

**Comment by User-noob2036876** [comment]
> > > No need to restart. It will applied new thumbnail when you refresh the page
> > 
> > 
> > Refresh not changes anything but waiting in app after refreshing changes thumbnail ¿
> 
> it is hard to see the different. But you can turn off then go to an example channel (like Tom Scott). Then turn on it and go back

It works on channels without restart. Dont work without restart on tabs like subscriptions

**Comment by YT-Advanced** [comment]
> > > > No need to restart. It will applied new thumbnail when you refresh the page
> > > 
> > > 
> > > Refresh not changes anything but waiting in app after refreshing changes thumbnail ¿
> > 
> > 
> > it is hard to see the different. But you can turn off then go to an example channel (like Tom Scott). Then turn on it and go back
> 
> It works on channels without restart. Dont work without restart on tabs like subscriptions

Ah, I see
