### ISSUE TITLE
bug: Seekbar thumbnail not worked when enabled Spoof Player paramter Type

### ISSUE THREAD

**Issue by Kantotero** [YT-Advanced/RVX_BUG_CENTER#3]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

RVX Youtube v18.31.40

### Bug description

Playback issues at around 1:00 or above. I enable both "spoof player parameter" & "spoof player parameter type" to fix this but it's still "buffering". Seek preview are gone together with filmstrip overlay. 

### Steps to reproduce

Step 1: Enable Spoof Parameter patch
Step 2: watch a video that lasts more than 1 minute
Step 3: get the playback issue where the video gets "infinite buffering" time at around 1:00 mark or beyond.
Step 4: I tried enabling "spoof parameter type" then disable "spoof parameter". Those two are different patches btw
Step 5: still get the same playback issue

### Relevant log output

```shell
n/a
```

### Screenshots or videos

![IMG_20230820_154203](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/125627064/2939d963-c17c-4bf4-942d-dea9b7301b4c)
In this method seek preview & filmstrip overlay works but has playback issue.

![IMG_20230820_154219](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/125627064/a163ea22-7674-4959-afe9-9d9694839869)
Same with the first pic, when turning on only "Spoof player parameter Type" it has seek preview but always playback issue

![IMG_20230820_154231](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/125627064/8ee78c64-0392-43e8-b1be-8dc31aec7994)
This fixes the playback issue but no more Seek Preview & Filmstrip overlay... 

### Solution

I fixed the playback issue by enabling both "Spoof player Parameter" & "spoof player parameter type" but the Seek Preview and filmstrip overlay will be gone. Can you make a work-around for Seek preview and filmstrip overlay to work while seeking or sliding the seekbar of a video.

### Device Environment

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by YT-Advanced** [comment]
Currently, it is know issues and not easy to solve

**Comment by Kantotero** [comment]
> Currently, it is know issues and not easy to solve

Okay.. just wanna hope you could make a work-around please.. I want seek preview feature while I enable "spoof player parameter" and "spoof player parameter type" patches. Also can you please add support for the newer latest versions of YT. Ver 18.33.35 is available right now...

**Comment by YT-Advanced** [comment]
> > Currently, it is know issues and not easy to solve
> 
> Okay.. just wanna hope you could make a work-around please.. I want seek preview feature while I enable "spoof player parameter" and "spoof player parameter type" patches. Also can you please add support for the newer latest versions of YT. Ver 18.33.35 is available right now...

Yes, of course. But I will release it tommorow

**Comment by Kantotero** [comment]
Okay thank you bro.. just letting you know of this issue I got... It would probably get fixed by revanced later on as they're the original but if you manage to fix it earlier then it'll be better outcome.. but no pressure, take your time bro..

**Comment by cyberboh** [comment]
@YT-Advanced @Kantotero 
this is side effect of "spoofs" and won't be fixed
see https://github.com/ReVanced/revanced-patches-template/issues/499

**Comment by YT-Advanced** [comment]
@cyberboh I know it, and don't tag me, I'm very busy
