### ISSUE TITLE
bug: <"Hide YouTube Premium Promotion" patch not working properly>

### ISSUE THREAD

**Issue by Rairof** [YT-Advanced/RVX_BUG_CENTER#4]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.31.40

### Bug description

Blocking of YouTube premium promotion banner doesn't work properly and I get a premium promotion pop up at random time when I onpe ReVanced extended.

### Steps to reproduce

Step 1. Patch ReVanced Extended with YT-Advanced patches
Step 2. Make sure "Hide YouTube Premium promotion" patch is enabled under Ads catagory in ReVanced Extended settings
Steps 3. open and close the app a few times and you should see premium promotion banner.

### Relevant log output

```shell
No logs needed
```

### Screenshots or videos

![Screenshot_2023-08-20-23-15-59-848_app rvx android youtube-edit](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/107706560/dab3d944-5837-4353-b8eb-86ba8bbfbeb5)

### Solution

Fixing the relevant patch.

### Additional context

Using Xiaomi 11T pro phone if that helps.

### Device Environment

Android 13 MIUI 14.0.4

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by vippium** [comment]
Yup...I agree with it. I reinstalled YT in A30 (Samsung) and got this newly very beautiful Premium banner.
