### ISSUE TITLE
feat(patch): Adding features to mMicrog

### ISSUE THREAD

**Issue by vippium** [YT-Advanced/RVX_BUG_CENTER#5]
### Application

mMicroG

### Issue

It will be great if you make mMicrog to be hidden from Launcher. As many of the people have stock andr. which doesn't support hiding apps. So, you can do either of the things :
1. Adding a patch options for mMicrog in builder with Custom Icons patch.
2. Or, make "Hide from Launcher" patch inbuild in the mMicrog. So that, not patch is needed.

In inotia00 patch, Vanced microg has the inbuild ability. But he added patch support (ended after last release) for mMicrog.

### Patch

---

### Motivation

Will enhance the mMicrog

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.

**Comment by YT-Advanced** [comment]
I'm thinking about create my own MicroG

**Comment by vippium** [comment]
> I'm thinking about create my own MicroG

Idea is great... atleast getting rid of unnecessary options. But pls add "Hide from launcher" patch in ur Microg.

**Comment by YT-Advanced** [comment]
Yes of course
