### ISSUE TITLE
Not working: Hook Download Button In YouTube ReX [Experimental Flag]

### ISSUE THREAD

**Issue by whitecodes001** [YT-Advanced/RVX_BUG_CENTER#7]
### Type

Error at runtime

### Tools used

Revancify

### Application

YouTube 18.33.40

### Bug description

The feature is not working or broken 

### Steps to reproduce

Step 1 :  include 'overlay-button' patch 
Step 2 :  enable 'Hook download button' option in Settings > Revanced Extended> overlay button > External downloader settings  under experimental flags there will be the option 
Step 3 : open any video tap download button 
Now u will see oficial YouTube downloading page not the external download page for my case it's seal so it redirects to application picker page
![Screenshot_2023-08-30-01-56-44-77_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/89518552/c4a1002e-77fc-41fc-b3cf-fa5f08179a63)
![Screenshot_2023-08-30-01-57-03-09_d11ae654701a5fadb313ea6fa9a6836f](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/89518552/2ea8d301-4859-4ed8-9b05-536ac8eb521a)

### Relevant log output

```shell
....
```

### Device Environment

Android Version : 13 ;
UI version and name : RUI 4 ;
Running Software version : RMX3771_13.1.0.535(EX01)
Phone brand : Realme
Phone name / Model : Realme 11 pro (RMX3771) 
Phone  processor : MT Dimensity 7050 ( i forgot the architecture but it something 64)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by YT-Advanced** [comment]
It required Premium account to use it

https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/70064328/df0672cc-60c4-40e3-a887-989a88d5557e
