### ISSUE TITLE
bug: `Hide audio track button` option present without selection 

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [YT-Advanced/RVX_BUG_CENTER#9]
### Type

Error at runtime

### Tools used

ReVanced Manager

### Application

YouTube v18.34.37

### Bug description

I haven't selected the patch `Hide Music Button` but still the setting shows up inside player within RVX settings.

### Steps to reproduce

1) Patch YT without selecting `Hide Music Button`.
2) Go into RVX settings and open Player.
3) Notice how `Hide audio track button` option is present.

### Relevant log output

```shell
Nil
```

### Screenshots or videos

Patches selected:
![Screenshot_20230906-210758~2](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/117499019/89dec45e-e021-4e9f-8d3c-2c256f54597b)

Option present within settings even though not selected:
![Screenshot_20230906-210731~2](https://github.com/YT-Advanced/RVX_BUG_CENTER/assets/117499019/b1c5f678-e908-4613-bf92-f650761c34ad)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by YT-Advanced** [comment]
Exclude `Hide layout components` patch

**Comment by ILoveOpenSourceApplications** [comment]
But that's just a work around right. What if I do want to hide certain layout components? And also this patch should be related to player and not the layout, I don't understand why it's getting included when the user isn't selecting the patch option itself.

**Comment by YT-Advanced** [comment]
@ILoveOpenSourceApplications I am not sure why inotia move it into layout compoment 🤔
